const productConstants = {
    GET_PRODUCT_LIST_REQUEST: "GET_PRODUCT_LIST_REQUEST",
    GET_PRODUCT_LIST_SUCCESS:"GET_PRODUCT_LIST_SUCCESS",
    GET_PRODUCT_LIST_FAIL:"GET_PRODUCT_LIST_FAIL",
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS:"GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL:"GET_PRODUCT_FAIL",

}

export default productConstants